volumes:
  postgres_data:

networks:
  homesense-network:

services:
  homesense-ui:
    image: ${UI_IMAGE:-homesense-ui}:${UI_VERSION:-latest}
    container_name: homesense-ui
    ports:
      - "4000:4000"
    restart: "unless-stopped"
  homesense-api:
    image: ${API_IMAGE:-homesense-api}:${API_VERSION:-latest}
    container_name: homesense-api
    ports:
      - "8080:8080"
    networks:
      homesense-network:
    restart: "unless-stopped"
    env_file: .env
  postgres:
    image: ${DATABASE_IMAGE:-postgres:14-alpine}
    container_name: postgres
    networks:
      homesense-network:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: "unless-stopped"
    env_file: .env
